apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "harbor.fullname" . }}-jobservice"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: jobservice
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: jobservice
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: jobservice
    spec:
      containers:
      - name: jobservice
        image: {{ .Values_jobservice_image_repository }}:{{ .Values_jobservice_image_tag }}
        imagePullPolicy: {{ .Values_jobservice_image_pullPolicy }}
        envFrom:
        - secretRef:
            name: "harbor-key-file"
        env:
        - name: LOG_LEVEL
          value: debug
        - name: CONFIG_PATH
          value: /etc/jobservice/app.conf
        - name: GODEBUG
          value: netdns=cgo
        - name: ADMINSERVER_URL
          value: "http://{{ template "harbor.fullname" . }}-adminserver"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jobservice-config
          mountPath: /etc/jobservice/app.conf
          subPath: app.conf
        - name: jobservice-secrets
          mountPath: /etc/jobservice/key
          subPath: key
      volumes:
      - name: jobservice-config
        configMap:
          name: "{{ template "harbor.fullname" . }}-jobservice"
      - name: jobservice-secrets
        secret:
          secretName: "harbor-key-file"
          items:
          - key: secretKey
            path: key
