apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.fullname" . }}-redis"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: redis
