apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
data:
  {{ if .Values.mysql_host -}}
  MYSQL_HOST: "{{ .Values.mysql_host }}"
  {{ else -}}
  MYSQL_HOST: "{{ template "harbor.fullname" . }}-mysql"
  {{ end -}}
  MYSQL_PORT: "{{ .Values.mysql_port }}"
  MYSQL_USR: "{{ .Values.mysql_user }}"
  MYSQL_DATABASE: "{{ .Values.mysql_database }}"
  MYSQL_PWD: "{{ .Values.mysql_pwd }}"
  EXT_ENDPOINT: "https://{{ .Values.externalDomain }}"
  UI_URL: "http://{{ template "harbor.fullname" . }}-ui"
  JOBSERVICE_URL: "http://{{ template "harbor.fullname" . }}-jobservice"
  REGISTRY_URL: "http://{{ template "harbor.fullname" . }}-registry:5000"
  TOKEN_SERVICE_URL: "http://{{ template "harbor.fullname" . }}-ui/service/token"
  WITH_NOTARY: "false"
  LOG_LEVEL: "info"
  IMAGE_STORE_PATH: "/" # This is a temporary hack.
  AUTH_MODE: "{{ .Values.adminserver_authenticationMode }}"
  SELF_REGISTRATION: "{{ .Values.adminserver_selfRegistration }}"
  LDAP_URL: "{{ .Values.adminserver_ldap_url }}"
  LDAP_SEARCH_DN: "{{ .Values.adminserver_ldap_searchDN }}"
  LDAP_SEARCH_PWD: "{{ .Values.adminserver_ldap_searchPWD }}"
  LDAP_BASE_DN: "{{ .Values.adminserver_ldap_baseDN }}"
  LDAP_UID: "{{ .Values.adminserver_ldap_uid }}"
  LDAP_SCOPE: "{{ .Values.adminserver_ldap_scope }}"
  LDAP_TIMEOUT: "{{ .Values.adminserver_ldap_timeout }}"
  DATABASE_TYPE: "mysql"
  PROJECT_CREATION_RESTRICTION: "everyone"
  VERIFY_REMOTE_CERT: "off"
  MAX_JOB_WORKERS: "5"
  TOKEN_EXPIRATION: "120"
  CFG_EXPIRATION: "5"
  GODEBUG: "netdns=cgo"
  ADMIRAL_URL: "NA"
  RESET: "false"
  WITH_CLAIR: "false"
