apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "harbor.fullname" . }}-ui"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
{{ include "harbor.matchLabels" . | indent 8 }}
        component: ui
    spec:
      containers:
      - name: ui
        image: {{ .Values_ui_image_repository }}:{{ .Values_ui_image_tag }}
        imagePullPolicy: {{ .Values_ui_image_pullPolicy }}
        envFrom:
        - secretRef:
            name: "harbor-key-file"
        env:
          - name: GODEBUG
            value: netdns=cgo
          - name: LOG_LEVEL
            value: debug
          - name: CONFIG_PATH
            value: /etc/ui/app.conf
          - name: ADMINSERVER_URL
            value: "http://{{ template "harbor.fullname" . }}-adminserver"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: ui-config
          mountPath: /etc/ui/app.conf
          subPath: app.conf
        - name: ui-secrets-key
          mountPath: /etc/ui/key
          subPath: key
        - name: ui-secrets-private-key
          mountPath: /etc/ui/private_key.pem
          subPath: private_key.pem
      volumes:
      - name: ui-config
        configMap:
          name: "{{ template "harbor.fullname" . }}-ui"
      - name: ui-secrets-key
        secret:
          secretName: "harbor-key-file"
          items:
            - key: secretKey
              path: key
      - name: ui-secrets-private-key
        secret:
          secretName: "harbor-key-file"
          items:
            - key: private_key.pem
              path: private_key.pem
